# Generated by Django 2.2.6 on 2019-11-03 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('Image', models.ImageField(null=True, upload_to='User/')),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 3, 20, 55, 26, 882582))),
                ('type', models.CharField(max_length=5)),
            ],
        ),
    ]
