# Generated by Django 2.2.6 on 2019-11-05 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('Image', models.ImageField(null=True, upload_to='User/')),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 52, 17, 846145))),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
