# Generated by Django 2.2.6 on 2019-11-03 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191103_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 21, 37, 6, 566090)),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
