# Generated by Django 2.2.6 on 2019-11-04 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191104_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 20, 54, 55, 364635)),
        ),
    ]
