# Generated by Django 2.2.6 on 2019-11-04 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191104_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 21, 36, 45, 87434)),
        ),
    ]
