# Generated by Django 2.2.6 on 2019-11-04 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 20, 54, 55, 357635))),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('seller', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(to='product.Category')),
            ],
        ),
    ]
