# Generated by Django 2.2.6 on 2019-11-04 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('seller_id', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 21, 36, 45, 17822))),
            ],
        ),
    ]
